"""add OrkaFin persistence

Revision ID: 36475e375cb5
Revises:
Create Date: 2026-07-13 04:45:29.661819
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "36475e375cb5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "action_proposals",
        sa.Column("proposal_id", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=8), nullable=False),
        sa.Column("action_id", sa.String(length=64), nullable=False),
        sa.Column("action_version", sa.String(length=32), nullable=False),
        sa.Column("owner_app_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("proposed_by_user_id", sa.String(length=64), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("workspace_app_id", sa.String(length=64), nullable=False),
        sa.Column("target_app_id", sa.String(length=64), nullable=False),
        sa.Column("target_entity_type", sa.String(length=64), nullable=False),
        sa.Column("target_entity_id", sa.String(length=64), nullable=False),
        sa.Column("parameters_json", sa.JSON(), nullable=False),
        sa.Column("parameter_hash", sa.String(length=64), nullable=False),
        sa.Column("preview_json", sa.JSON(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('proposed', 'confirmed', 'cancelled', 'expired', 'executed', 'failed')",
            name="ck_action_proposals_status",
        ),
        sa.PrimaryKeyConstraint("proposal_id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_action_proposals_request_id"), "action_proposals", ["request_id"], unique=False
    )
    op.create_index(
        "ix_action_proposals_user_created",
        "action_proposals",
        ["proposed_by_user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "audit_records",
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=8), nullable=False),
        sa.Column("event_type", sa.String(length=48), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("actor_user_id", sa.String(length=64), nullable=True),
        sa.Column("workspace_id", sa.String(length=64), nullable=True),
        sa.Column("app_id", sa.String(length=64), nullable=False),
        sa.Column("target_app_id", sa.String(length=64), nullable=True),
        sa.Column("target_entity_type", sa.String(length=64), nullable=True),
        sa.Column("target_entity_id", sa.String(length=64), nullable=True),
        sa.Column("action_id", sa.String(length=64), nullable=True),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("correlation_id", sa.String(length=36), nullable=False),
        sa.Column("details_json", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "event_type IN ("
            "'identity_verified', 'identity_denied', 'candidate_read', "
            "'permission_denied', 'action_proposed', 'action_confirmation_issued', "
            "'action_confirmed', 'action_confirmation_rejected', "
            "'action_confirmation_expired', 'action_tampering_rejected', "
            "'action_execution_attempted', 'action_execution_succeeded', "
            "'action_execution_failed', 'action_execution_unknown')",
            name="ck_audit_records_event_type",
        ),
        sa.CheckConstraint(
            "outcome IN ('allowed', 'denied', 'succeeded', 'failed', 'unknown')",
            name="ck_audit_records_outcome",
        ),
        sa.PrimaryKeyConstraint("audit_id"),
    )
    op.create_index(
        "ix_audit_records_correlation", "audit_records", ["correlation_id"], unique=False
    )
    op.create_index("ix_audit_records_occurred", "audit_records", ["occurred_at"], unique=False)
    op.create_index(
        op.f("ix_audit_records_request_id"), "audit_records", ["request_id"], unique=False
    )
    op.execute(
        "CREATE TRIGGER prevent_audit_records_update "
        "BEFORE UPDATE ON audit_records BEGIN "
        "SELECT RAISE(ABORT, 'audit_records are append-only'); END"
    )
    op.execute(
        "CREATE TRIGGER prevent_audit_records_delete "
        "BEFORE DELETE ON audit_records BEGIN "
        "SELECT RAISE(ABORT, 'audit_records are append-only'); END"
    )
    op.create_table(
        "conversations",
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=8), nullable=False),
        sa.Column("owner_user_id", sa.String(length=64), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("workspace_app_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('active', 'closed')", name="ck_conversations_status"),
        sa.PrimaryKeyConstraint("conversation_id"),
    )
    op.create_index(
        "ix_conversations_owner_workspace",
        "conversations",
        ["owner_user_id", "workspace_id"],
        unique=False,
    )
    op.create_table(
        "recommendations",
        sa.Column("recommendation_id", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=8), nullable=False),
        sa.Column("rule_id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("recipient_user_id", sa.String(length=64), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("workspace_app_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("body", sa.String(length=500), nullable=False),
        sa.Column("rationale", sa.String(length=500), nullable=False),
        sa.Column("feature_id", sa.String(length=64), nullable=True),
        sa.Column("action_id", sa.String(length=64), nullable=True),
        sa.Column("source_ids", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint(
            "kind IN ('feature', 'next_step', 'productivity_nudge')", name="ck_recommendations_kind"
        ),
        sa.CheckConstraint(
            "status IN ('proposed', 'shown', 'accepted', 'dismissed', 'expired')",
            name="ck_recommendations_status",
        ),
        sa.PrimaryKeyConstraint("recommendation_id"),
    )
    op.create_index(
        "ix_recommendations_recipient_created",
        "recommendations",
        ["recipient_user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendations_request_id"), "recommendations", ["request_id"], unique=False
    )
    op.create_table(
        "user_events",
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=8), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("app_id", sa.String(length=64), nullable=False),
        sa.Column("actor_user_id", sa.String(length=64), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("workspace_app_id", sa.String(length=64), nullable=False),
        sa.Column("entity_app_id", sa.String(length=64), nullable=True),
        sa.Column("entity_type", sa.String(length=64), nullable=True),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("correlation_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint(
            "event_type IN ("
            "'app_opened', 'page_viewed', 'candidate_selected', "
            "'assistant_query_submitted', 'recommendation_shown', "
            "'recommendation_accepted', 'recommendation_dismissed', "
            "'feedback_submitted', 'action_proposed', 'action_confirmed', "
            "'action_succeeded', 'action_failed')",
            name="ck_user_events_type",
        ),
        sa.CheckConstraint(
            "source IN ('orkafin', 'owning_application')", name="ck_user_events_source"
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        "ix_user_events_actor_occurred",
        "user_events",
        ["actor_user_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_events_correlation_id"), "user_events", ["correlation_id"], unique=False
    )
    op.create_index(op.f("ix_user_events_request_id"), "user_events", ["request_id"], unique=False)
    op.create_index(
        "ix_user_events_workspace_occurred",
        "user_events",
        ["workspace_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "action_confirmations",
        sa.Column("confirmation_id", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=8), nullable=False),
        sa.Column("proposal_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("bound_user_id", sa.String(length=64), nullable=False),
        sa.Column("bound_workspace_id", sa.String(length=64), nullable=False),
        sa.Column("parameter_hash", sa.String(length=64), nullable=False),
        sa.Column("confirmation_secret_hash", sa.String(length=64), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('issued', 'accepted', 'rejected', 'expired', 'consumed')",
            name="ck_action_confirmations_status",
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"], ["action_proposals.proposal_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("confirmation_id"),
    )
    op.create_index(
        "ix_action_confirmations_proposal", "action_confirmations", ["proposal_id"], unique=False
    )
    op.create_table(
        "action_executions",
        sa.Column("execution_id", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=8), nullable=False),
        sa.Column("proposal_id", sa.String(length=64), nullable=False),
        sa.Column("action_id", sa.String(length=64), nullable=False),
        sa.Column("action_version", sa.String(length=32), nullable=False),
        sa.Column("owner_app_id", sa.String(length=64), nullable=False),
        sa.Column("target_app_id", sa.String(length=64), nullable=False),
        sa.Column("target_entity_type", sa.String(length=64), nullable=False),
        sa.Column("target_entity_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("adapter_receipt_json", sa.JSON(), nullable=True),
        sa.Column("safe_message", sa.String(length=500), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('succeeded', 'failed', 'unknown', 'conflict', 'rejected')",
            name="ck_action_executions_status",
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"], ["action_proposals.proposal_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("execution_id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        "ix_action_executions_proposal", "action_executions", ["proposal_id"], unique=False
    )
    op.create_index(
        op.f("ix_action_executions_request_id"), "action_executions", ["request_id"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("message_id", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=8), nullable=False),
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source_ids", sa.JSON(), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role IN ('user', 'assistant')", name="ck_messages_role"),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.conversation_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("message_id"),
    )
    op.create_index(
        "ix_messages_conversation_created",
        "messages",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_messages_request_id"), "messages", ["request_id"], unique=False)
    op.create_table(
        "recommendation_feedback",
        sa.Column("feedback_id", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=8), nullable=False),
        sa.Column("recommendation_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("workspace_app_id", sa.String(length=64), nullable=False),
        sa.Column("feedback_type", sa.String(length=16), nullable=False),
        sa.Column("comment", sa.String(length=500), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.CheckConstraint(
            "feedback_type IN ('helpful', 'not_helpful', 'accepted', 'dismissed')",
            name="ck_recommendation_feedback_type",
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_id"], ["recommendations.recommendation_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("feedback_id"),
    )
    op.create_index(
        "ix_recommendation_feedback_recommendation",
        "recommendation_feedback",
        ["recommendation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendation_feedback_request_id"),
        "recommendation_feedback",
        ["request_id"],
        unique=False,
    )
    op.create_table(
        "recommendation_impressions",
        sa.Column("impression_id", sa.String(length=64), nullable=False),
        sa.Column("recommendation_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("shown_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["recommendation_id"], ["recommendations.recommendation_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("impression_id"),
    )
    op.create_index(
        "ix_recommendation_impressions_recommendation_shown",
        "recommendation_impressions",
        ["recommendation_id", "shown_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendation_impressions_request_id"),
        "recommendation_impressions",
        ["request_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # SQLite triggers enforce append-only audit semantics and must be removed first.
    op.drop_index(
        op.f("ix_recommendation_impressions_request_id"), table_name="recommendation_impressions"
    )
    op.drop_index(
        "ix_recommendation_impressions_recommendation_shown",
        table_name="recommendation_impressions",
    )
    op.drop_table("recommendation_impressions")
    op.drop_index(
        op.f("ix_recommendation_feedback_request_id"), table_name="recommendation_feedback"
    )
    op.drop_index("ix_recommendation_feedback_recommendation", table_name="recommendation_feedback")
    op.drop_table("recommendation_feedback")
    op.drop_index(op.f("ix_messages_request_id"), table_name="messages")
    op.drop_index("ix_messages_conversation_created", table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_action_executions_request_id"), table_name="action_executions")
    op.drop_index("ix_action_executions_proposal", table_name="action_executions")
    op.drop_table("action_executions")
    op.drop_index("ix_action_confirmations_proposal", table_name="action_confirmations")
    op.drop_table("action_confirmations")
    op.drop_index("ix_user_events_workspace_occurred", table_name="user_events")
    op.drop_index(op.f("ix_user_events_request_id"), table_name="user_events")
    op.drop_index(op.f("ix_user_events_correlation_id"), table_name="user_events")
    op.drop_index("ix_user_events_actor_occurred", table_name="user_events")
    op.drop_table("user_events")
    op.drop_index(op.f("ix_recommendations_request_id"), table_name="recommendations")
    op.drop_index("ix_recommendations_recipient_created", table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index("ix_conversations_owner_workspace", table_name="conversations")
    op.drop_table("conversations")
    op.execute("DROP TRIGGER prevent_audit_records_delete")
    op.execute("DROP TRIGGER prevent_audit_records_update")
    op.drop_index(op.f("ix_audit_records_request_id"), table_name="audit_records")
    op.drop_index("ix_audit_records_occurred", table_name="audit_records")
    op.drop_index("ix_audit_records_correlation", table_name="audit_records")
    op.drop_table("audit_records")
    op.drop_index("ix_action_proposals_user_created", table_name="action_proposals")
    op.drop_index(op.f("ix_action_proposals_request_id"), table_name="action_proposals")
    op.drop_table("action_proposals")
    # ### end Alembic commands ###
